[package]
name = "radio_datetime_utils"
version = "0.1.0"
edition = "2021"
authors = [ "rene0" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.7.13"
